package br.ufpr.inf.heuchess.telas.editorheuristica;

import br.ufpr.inf.heuchess.representacao.heuristica.Regiao;
import java.awt.Component;
import javax.swing.Icon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Alexandre Rômolo Moreira Feitosa - alexandreromolo@hotmail.com
 * Created on 4 de Agosto de 2006, 16:12
 */
public class RenderListaRegioes extends javax.swing.JPanel implements ListCellRenderer {
    
    public static int posXCheckBox;    
    public static int widthCheckBox;
    
    public RenderListaRegioes() {
        initComponents();       
    }
    
    public static boolean dentroCheckBox(int x){
        
        if (x >= posXCheckBox && x <= (posXCheckBox + widthCheckBox)){
            return true;
        }else{
            return false;
        }
    }
    
    @Override
    public Component getListCellRendererComponent(JList list,
                                                  Object value,
                                                  int index,
                                                  boolean isSelected,
                                                  boolean hasFocus) {
        
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
            jLabelNomeRegiao.setBackground(list.getSelectionBackground());
            jLabelNomeRegiao.setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
            jLabelNomeRegiao.setBackground(list.getBackground());
            jLabelNomeRegiao.setForeground(list.getForeground());
        }        
        
        setEnabled(list.isEnabled());
        
        posXCheckBox  = jCheckBoxVisivel.getX();        
        widthCheckBox = jCheckBoxVisivel.getWidth();
        
        if (value instanceof Regiao){
            
            Regiao atual = (Regiao) value;
            
            jLabelIcon.setIcon((Icon) atual.getColorIcon());
            jLabelNomeRegiao.setText(atual.getNome());
            jCheckBoxVisivel.setSelected(atual.isVisivel());            
        }
        
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxVisivel = new javax.swing.JCheckBox();
        jLabelNomeRegiao = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();

        jCheckBoxVisivel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxVisivel.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabelNomeRegiao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomeRegiao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelIcon.setIconTextGap(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxVisivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeRegiao, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBoxVisivel)
                .addComponent(jLabelNomeRegiao)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxVisivel;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelNomeRegiao;
    // End of variables declaration//GEN-END:variables
}
