package br.ufpr.inf.heuchess.telas.iniciais;

import br.ufpr.inf.heuchess.HeuChess;
import br.ufpr.inf.heuchess.representacao.organizacao.Usuario;
import br.ufpr.inf.utils.gui.ModalFrameHierarchy;
import br.ufpr.inf.utils.gui.ModalFrameUtil;
import br.ufpr.inf.utils.gui.UtilsGUI;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre Rômolo Moreira Feitosa - alexandreromolo@hotmail.com
 * @since  Aug 3, 2012
 */
public class TelaTrocaSenha extends javax.swing.JFrame implements ModalFrameHierarchy {
    
    private AcessoTelaTrocaSenha acessoTelaTrocaSenha;    
    private Usuario              usuario;
    
    private boolean avisoTeclaCapsLock;
    
    public TelaTrocaSenha(AcessoTelaTrocaSenha acessoTelaTrocaSenha, Usuario usuario) {
        
        this.acessoTelaTrocaSenha = acessoTelaTrocaSenha;
        this.usuario              = usuario;
                
        initComponents();        
        
        ModalFrameUtil.showAsModalDontBlock(this); 
        jPasswordFieldSenhaAtual.requestFocus();        
    }
    
    @Override
    public Frame getFrame(){
        return this;        
    }
    
    @Override
    public ModalFrameHierarchy getModalOwner(){
        return acessoTelaTrocaSenha;
    } 
    
    private void confirmaCancelar() {

        int resposta = UtilsGUI.dialogoConfirmacao(this, "Deseja realmente cancelar as alterações feitas?", "Confirmação Cancelamento");
        if (resposta == JOptionPane.NO_OPTION || resposta == -1) {
            return;
        }

        dispose();
        acessoTelaTrocaSenha.fechandoTelaTrocaSenha(null);
    }
    
    private void confirmaTroca(){
        
        String senhaAtualDigitada = new String(jPasswordFieldSenhaAtual.getPassword());
        
        if (senhaAtualDigitada.length() == 0){            
            UtilsGUI.dialogoErro(this,"O campo Senha atual está vazio!");
            jPasswordFieldSenhaAtual.requestFocus();
            return;
        }
                
        // Valida senha atual //
        
        if (!HeuChess.verificaSenhas(senhaAtualDigitada,usuario.getSenha())){        
            UtilsGUI.dialogoErro(this,"A Senha atual digitada não é válida!");
            jPasswordFieldSenhaAtual.setText(null);
            jPasswordFieldSenhaAtual.requestFocus();
            return;
        }
        
        // Valida nova senha //
        
        String novaSenha1 = new String(jPasswordFieldSenhaNova1.getPassword());
        if (novaSenha1.length() == 0){            
            UtilsGUI.dialogoErro(this,"O campo Nova Senha está vazio!");
            jPasswordFieldSenhaNova1.requestFocus();
            return;
        }
        
        String novaSenha2 = new String(jPasswordFieldSenhaNova2.getPassword());
        if (novaSenha2.length() == 0){            
            UtilsGUI.dialogoErro(this,"O campo de confirmação da Nova Senha está vazio!");
            jPasswordFieldSenhaNova2.requestFocus();
            return;
        }
        
        if (!novaSenha1.equals(novaSenha2)){
            UtilsGUI.dialogoErro(this,"A confirmação da nova senha não é válida!");
            jPasswordFieldSenhaNova2.setText(null);
            jPasswordFieldSenhaNova2.requestFocus();
            return;
        }
        
        if (novaSenha1.length() < 6){
            UtilsGUI.dialogoErro(this,"A Nova Senha deve ter no mínimo 6 caracteres!");
            jPasswordFieldSenhaNova2.setText(null);
            jPasswordFieldSenhaNova1.setText(null);
            jPasswordFieldSenhaNova1.requestFocus();
            return;
        }
        
        dispose();
        acessoTelaTrocaSenha.fechandoTelaTrocaSenha(novaSenha1); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordFieldSenhaAtual = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldSenhaNova1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldSenhaNova2 = new javax.swing.JPasswordField();
        jPanelBase = new javax.swing.JPanel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Troca Senha");
        setIconImage(new ImageIcon(getClass().getResource("/icones/reset16.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Senha Atual");

        jPasswordFieldSenhaAtual.setToolTipText("Entre com a senha atual");
        jPasswordFieldSenhaAtual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaAtualFocusGained(evt);
            }
        });

        jLabel1.setText("Nova Senha");

        jPasswordFieldSenhaNova1.setToolTipText("Entre com a nova senha");
        jPasswordFieldSenhaNova1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaNova1FocusGained(evt);
            }
        });

        jLabel2.setText("Confirma nova Senha");

        jPasswordFieldSenhaNova2.setToolTipText("Confirme novamente a nova senha");
        jPasswordFieldSenhaNova2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaNova2ActionPerformed(evt);
            }
        });
        jPasswordFieldSenhaNova2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaNova2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldSenhaNova2))
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldSenhaAtual)
                            .addComponent(jPasswordFieldSenhaNova1))))
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jPasswordFieldSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordFieldSenhaNova1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldSenhaNova2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icone_confirmar.png"))); // NOI18N
        jButtonConfirmar.setMnemonic('C');
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icone_cancelar.png"))); // NOI18N
        jButtonCancelar.setMnemonic('n');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonConfirmar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConfirmar)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonConfirmar});

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-319)/2, (screenSize.height-240)/2, 319, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        confirmaCancelar();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        confirmaTroca();                        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        confirmaCancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPasswordFieldSenhaNova2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNova2ActionPerformed
        confirmaTroca();
    }//GEN-LAST:event_jPasswordFieldSenhaNova2ActionPerformed

    private void jPasswordFieldSenhaAtualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaAtualFocusGained
        
        if (!avisoTeclaCapsLock){
            avisoTeclaCapsLock = HeuChess.verificaTeclaCapsLock(jPasswordFieldSenhaAtual);    
        }
    }//GEN-LAST:event_jPasswordFieldSenhaAtualFocusGained

    private void jPasswordFieldSenhaNova1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNova1FocusGained
        
        if (!avisoTeclaCapsLock){
            avisoTeclaCapsLock = HeuChess.verificaTeclaCapsLock(jPasswordFieldSenhaNova1);
        }
    }//GEN-LAST:event_jPasswordFieldSenhaNova1FocusGained

    private void jPasswordFieldSenhaNova2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNova2FocusGained
        
        if (!avisoTeclaCapsLock){
            avisoTeclaCapsLock = HeuChess.verificaTeclaCapsLock(jPasswordFieldSenhaNova2);
        }
    }//GEN-LAST:event_jPasswordFieldSenhaNova2FocusGained
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPasswordField jPasswordFieldSenhaAtual;
    private javax.swing.JPasswordField jPasswordFieldSenhaNova1;
    private javax.swing.JPasswordField jPasswordFieldSenhaNova2;
    // End of variables declaration//GEN-END:variables
}