package br.ufpr.inf.heuchess.telas.iniciais;

import br.ufpr.inf.heuchess.Anotacoes;
import br.ufpr.inf.heuchess.HeuChess;
import br.ufpr.inf.heuchess.persistencia.AnotacaoDAO;
import br.ufpr.inf.heuchess.persistencia.ConexaoDBHeuChess;
import br.ufpr.inf.heuchess.persistencia.ConjuntoHeuristicoDAO;
import br.ufpr.inf.heuchess.persistencia.EtapaDAO;
import br.ufpr.inf.heuchess.representacao.heuristica.*;
import br.ufpr.inf.utils.gui.DocumentMasked;
import br.ufpr.inf.utils.gui.ModalFrameHierarchy;
import br.ufpr.inf.utils.gui.ModalFrameUtil;
import br.ufpr.inf.utils.gui.UtilsGUI;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Alexandre Rômolo Moreira Feitosa - alexandreromolo@hotmail.com
 * Created on 28 de Junho de 2006, 14:55
 */
public class TelaNovoConjuntoHeuristico extends javax.swing.JFrame implements ModalFrameHierarchy {
    
    private CardLayout card;
    private int        etapaCriacao;    
        
    public TelaNovoConjuntoHeuristico() {
        
        etapaCriacao  = 1;
        
        initComponents();
        
        card = (CardLayout) jPanelPrincipal.getLayout();                
        jButtonAnterior.setVisible(false);
        
        configuraTextoComplexidade();
        
        jLabelIcone.setIcon(Anotacoes.retornaIconeAnotacao((Tipo)jComboBoxTipoAnotacao.getSelectedItem()));
                
        ModalFrameUtil.showAsModalDontBlock(this); 
    }
    
    @Override
    public Frame getFrame(){
        return this;
    }
    
    @Override
    public ModalFrameHierarchy getModalOwner(){
        return HeuChess.telaPrincipal;
    }
    
    private void configuraTextoComplexidade(){        
        
        Tipo tipo = ConjuntoHeuristicoDAO.nivelOrdem(jSliderNivelComplexidade.getValue());
        if (tipo != null){
            jTextAreaExplicacaoComplexidade.setText("Nível "+ ConjuntoHeuristicoDAO.ordemNivel(tipo) + " - " + tipo.getNome() + "\n\n" + tipo.getDescricao());            
        }
    }
    
    private void habilitaProximoPasso1(){
        
        if (jTextFieldNomeConjuntoHeuristico.getText().trim().length() > 0){
            jButtonProximo.setEnabled(true);
        }else{
            jButtonProximo.setEnabled(false);
        }
    }
    
    public void cancelaCriacao(){
        
        int resposta = UtilsGUI.dialogoConfirmacao(this,"Deseja Cancelar a Criação?","Confirma Cancelamento");
        if (resposta == JOptionPane.YES_OPTION){
            dispose();
            HeuChess.telaPrincipal.fechandoTelaNovoConjuntoHeuristico(null);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelPasso1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeConjuntoHeuristico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelPasso2 = new javax.swing.JPanel();
        jSliderNivelComplexidade = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaExplicacaoComplexidade = new javax.swing.JTextArea();
        jPanelPasso3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerValorPeao = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)); ;
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerValorTorre = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)); ;
        jSpinnerValorCavalo = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)); ;
        jSpinnerValorBispo = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)); ;
        jSpinnerValorDama = new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)); ;
        jTextFieldValorRei = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanelPasso4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTextoAnotacao = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTituloAnotacao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxTipoAnotacao = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelTotalCaracteres = new javax.swing.JLabel();
        jLabelIcone = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Novo Conjunto Heurístico");
        setIconImage(new ImageIcon(getClass().getResource("/icones/icone_conjunto_heuristico.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Nome");

        jTextFieldNomeConjuntoHeuristico.setDocument(new DocumentMasked(DHJOG.CARACTERES_VALIDOS,DocumentMasked.ONLY_CAPITAL));
        jTextFieldNomeConjuntoHeuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeConjuntoHeuristicoActionPerformed(evt);
            }
        });
        jTextFieldNomeConjuntoHeuristico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeConjuntoHeuristicoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Passo 1 de 4");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Defina um nome para o novo Conjunto Heurístico");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Observação:");

        jLabel21.setText("Só é permitido digitar letras sem acentos, ");

        jLabel22.setText("números, e o caracter \"_\" no nome de um componente.");

        javax.swing.GroupLayout jPanelPasso1Layout = new javax.swing.GroupLayout(jPanelPasso1);
        jPanelPasso1.setLayout(jPanelPasso1Layout);
        jPanelPasso1Layout.setHorizontalGroup(
            jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeConjuntoHeuristico))
                    .addGroup(jPanelPasso1Layout.createSequentialGroup()
                        .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(0, 268, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPasso1Layout.setVerticalGroup(
            jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addGap(30, 30, 30)
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeConjuntoHeuristico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelPasso1, "Passo1");

        jSliderNivelComplexidade.setMaximum(10);
        jSliderNivelComplexidade.setMinimum(1);
        jSliderNivelComplexidade.setMinorTickSpacing(1);
        jSliderNivelComplexidade.setPaintLabels(true);
        jSliderNivelComplexidade.setPaintTicks(true);
        jSliderNivelComplexidade.setSnapToTicks(true);
        jSliderNivelComplexidade.setValue(1);
        //jSliderNivelComplexidade.setMaximum(ConjuntoHeuristicoDAO.tiposConjuntoHeuristico.size());
        jSliderNivelComplexidade.setMaximum(4);
        jSliderNivelComplexidade.setLabelTable(jSliderNivelComplexidade.createStandardLabels(1));

        jSliderNivelComplexidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNivelComplexidadeStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Passo 2 de 4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Qual o nível de Complexidade?");

        jTextAreaExplicacaoComplexidade.setColumns(20);
        jTextAreaExplicacaoComplexidade.setEditable(false);
        jTextAreaExplicacaoComplexidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaExplicacaoComplexidade.setLineWrap(true);
        jTextAreaExplicacaoComplexidade.setRows(5);
        jTextAreaExplicacaoComplexidade.setWrapStyleWord(true);
        jTextAreaExplicacaoComplexidade.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jTextAreaExplicacaoComplexidade);

        javax.swing.GroupLayout jPanelPasso2Layout = new javax.swing.GroupLayout(jPanelPasso2);
        jPanelPasso2.setLayout(jPanelPasso2Layout);
        jPanelPasso2Layout.setHorizontalGroup(
            jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jSliderNivelComplexidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPasso2Layout.setVerticalGroup(
            jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderNivelComplexidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelPasso2, "Passo2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Passo 3 de 4");

        UtilsGUI.centralizaAutoValidaValorJSpinner(jSpinnerValorPeao, null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/peao.png"))); // NOI18N
        jLabel6.setText("Peão");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/torre.png"))); // NOI18N
        jLabel7.setText("Torre");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/cavalo.png"))); // NOI18N
        jLabel8.setText("Cavalo");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/bispo.png"))); // NOI18N
        jLabel9.setText("Bispo");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/dama.png"))); // NOI18N
        jLabel10.setText("Dama");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pecas/rei.png"))); // NOI18N
        jLabel11.setText("Rei");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Defina os valores iniciais de cada Peça no cálculo do Tabuleiro");

        UtilsGUI.centralizaAutoValidaValorJSpinner(jSpinnerValorTorre, null);

        UtilsGUI.centralizaAutoValidaValorJSpinner(jSpinnerValorCavalo, null);

        UtilsGUI.centralizaAutoValidaValorJSpinner(jSpinnerValorBispo, null);

        UtilsGUI.centralizaAutoValidaValorJSpinner(jSpinnerValorDama, null);

        jTextFieldValorRei.setEditable(false);
        jTextFieldValorRei.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldValorRei.setText("+INFINITO");

        jLabel19.setText("Valores válidos de 1 a 100");

        javax.swing.GroupLayout jPanelPasso3Layout = new javax.swing.GroupLayout(jPanelPasso3);
        jPanelPasso3.setLayout(jPanelPasso3Layout);
        jPanelPasso3Layout.setHorizontalGroup(
            jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerValorCavalo)
                    .addComponent(jSpinnerValorTorre)
                    .addComponent(jSpinnerValorPeao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerValorBispo, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jSpinnerValorDama)))
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldValorRei, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanelPasso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPasso3Layout.setVerticalGroup(
            jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerValorPeao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerValorTorre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSpinnerValorCavalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jSpinnerValorDama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldValorRei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSpinnerValorBispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelPasso3, "Passo3");

        jTextAreaTextoAnotacao.setColumns(20);
        jTextAreaTextoAnotacao.setLineWrap(true);
        jTextAreaTextoAnotacao.setRows(4);
        jTextAreaTextoAnotacao.setWrapStyleWord(true);
        jTextAreaTextoAnotacao.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextAreaTextoAnotacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaTextoAnotacaoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaTextoAnotacao);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Passo 4 de 4");

        jTextFieldTituloAnotacao.setText("Explicação Inicial");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Crie uma Anotação para explicar este novo Conjunto Heurístico");

        jLabel15.setText("Título ");

        for (Tipo tipo : AnotacaoDAO.tiposAnotacao){
            jComboBoxTipoAnotacao.addItem(tipo);
        }
        jComboBoxTipoAnotacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoAnotacaoItemStateChanged(evt);
            }
        });

        jLabel16.setText("Tipo");

        jLabel17.setText("Descrição");

        jLabelTotalCaracteres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalCaracteres.setText("Total de Caracteres = 0");

        jLabelIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcone.setIconTextGap(0);

        javax.swing.GroupLayout jPanelPasso4Layout = new javax.swing.GroupLayout(jPanelPasso4);
        jPanelPasso4.setLayout(jPanelPasso4Layout);
        jPanelPasso4Layout.setHorizontalGroup(
            jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloAnotacao)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTotalCaracteres, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addGroup(jPanelPasso4Layout.createSequentialGroup()
                        .addComponent(jLabelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                    .addGroup(jPanelPasso4Layout.createSequentialGroup()
                        .addGroup(jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPasso4Layout.setVerticalGroup(
            jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addGroup(jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxTipoAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTituloAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPasso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalCaracteres)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanelPasso4, "Passo4");

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icone_cancelar.png"))); // NOI18N
        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icone_avancar.png"))); // NOI18N
        jButtonProximo.setMnemonic('p');
        jButtonProximo.setText("Próximo");
        jButtonProximo.setEnabled(false);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icone_voltar.png"))); // NOI18N
        jButtonAnterior.setMnemonic('n');
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ajuda-pesquisar.png"))); // NOI18N
        jButtonAjuda.setMnemonic('a');
        jButtonAjuda.setText("Ajuda");
        jButtonAjuda.setToolTipText("Consulta o texto de ajuda desta tela");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonProximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAjuda, jButtonAnterior, jButtonCancelar, jButtonProximo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAjuda, jButtonAnterior, jButtonCancelar, jButtonProximo});

        setSize(new java.awt.Dimension(596, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeConjuntoHeuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeConjuntoHeuristicoActionPerformed
        jButtonProximoActionPerformed(null);
    }//GEN-LAST:event_jTextFieldNomeConjuntoHeuristicoActionPerformed

    private void jTextAreaTextoAnotacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaTextoAnotacaoKeyReleased
        
        String texto = jTextAreaTextoAnotacao.getText();
        
        if (texto != null){
            
            int totalTeclado = texto.length();        
            
            jLabelTotalCaracteres.setText("Total de Caracteres = " + totalTeclado);
        }
    }//GEN-LAST:event_jTextAreaTextoAnotacaoKeyReleased

    private void jTextFieldNomeConjuntoHeuristicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeConjuntoHeuristicoKeyReleased
        habilitaProximoPasso1();
    }//GEN-LAST:event_jTextFieldNomeConjuntoHeuristicoKeyReleased

    private void jComboBoxTipoAnotacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoAnotacaoItemStateChanged
        jLabelIcone.setIcon(Anotacoes.retornaIconeAnotacao((Tipo)jComboBoxTipoAnotacao.getSelectedItem()));
    }//GEN-LAST:event_jComboBoxTipoAnotacaoItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelaCriacao();
    }//GEN-LAST:event_formWindowClosing

    private void jSliderNivelComplexidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNivelComplexidadeStateChanged
        configuraTextoComplexidade();
    }//GEN-LAST:event_jSliderNivelComplexidadeStateChanged

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        
        etapaCriacao--;
        switch(etapaCriacao){
            
            case 1:card.show(jPanelPrincipal,"Passo1");
                   jButtonAnterior.setVisible(false);
                   habilitaProximoPasso1();
                   break;
                
            case 2:card.show(jPanelPrincipal,"Passo2");                   
                   break;
                
            case 3:card.show(jPanelPrincipal,"Passo3");
                   jButtonProximo.setText("Próximo"); 
                   jButtonProximo.setMnemonic('p');
                   break;            
        }        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        cancelaCriacao();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        
        if (jButtonProximo.getText().equalsIgnoreCase("Próximo")){
            
            if (etapaCriacao == 1) {
                
                setCursor(new Cursor(Cursor.WAIT_CURSOR));
                
                try {
                    long idConjuntoMesmoNome = ConjuntoHeuristicoDAO.existeNome(HeuChess.usuario, jTextFieldNomeConjuntoHeuristico.getText());
                    
                    if (idConjuntoMesmoNome != -1) {
                        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        UtilsGUI.dialogoErro(this, "Você já possui um Conjunto Heurístico com este nome!\nEscolha outro.");
                        return;
                    }
                } catch (Exception e) {
                    HeuChess.registraExcecao(e);
                    
                    setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    UtilsGUI.dialogoErro(this, "Erro ao procurar o Nome do Novo Conjunto Heurístico no Banco de Dados!");
                    return;
                }
                
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
            
            etapaCriacao++;
            switch(etapaCriacao){
                
                case 2:card.show(jPanelPrincipal,"Passo2");
                    jButtonAnterior.setVisible(true);
                    break;
                    
                case 3:card.show(jPanelPrincipal,"Passo3");
                    break;
                    
                case 4:card.show(jPanelPrincipal,"Passo4");
                    jButtonProximo.setText("Concluir");
                    jButtonProximo.setMnemonic('n');
                    break;             
            }
        }else{           
            
            ////////////////////////////////////
            // Criar Novo Conjunto Heurístico //       
            ////////////////////////////////////
            
            String titulo    = jTextFieldTituloAnotacao.getText();
            String descricao = jTextAreaTextoAnotacao.getText();
            
            boolean faltaDadosAnotacao = false;
            
            if (titulo == null || titulo.trim().length() == 0){
                faltaDadosAnotacao = true;
                int resposta = UtilsGUI.dialogoConfirmacao(this, "O título da Anotação não foi preenchido!\n" +
                                                                 "Deseja criar o novo Conjunto Heurístico sem uma Anotação Inicial?",
                                                                 "Aviso de Falta de Dados");
                
                if (resposta == JOptionPane.NO_OPTION || resposta == -1){
                    return;
                }
            }
            
            if (descricao == null || descricao.trim().length() == 0){
                faltaDadosAnotacao = true;
                int resposta = UtilsGUI.dialogoConfirmacao(this, "A descrição da Anotação Inicial não foi preenchido!\n" +
                                                                 "Deseja criar o novo Conjunto Heurístico sem uma Anotação Inicial?",
                                                                 "Aviso de Falta de Dados");
                
                if (resposta == JOptionPane.NO_OPTION || resposta == -1){
                    return;
                }
            }
             
            try{
                setCursor(new Cursor(Cursor.WAIT_CURSOR));
            
                ConjuntoHeuristico novoConjunto = new ConjuntoHeuristico(jTextFieldNomeConjuntoHeuristico.getText(),
                                                                         HeuChess.usuario.getId(),
                                                                         ConjuntoHeuristicoDAO.nivelOrdem(jSliderNivelComplexidade.getValue()));
             
                Etapa etapa = new Etapa(novoConjunto, "PADRAO", HeuChess.usuario.getId(), EtapaDAO.tiposEtapas.get(0));
            
                etapa.setValorPeao(((Integer)  jSpinnerValorPeao.getValue()).intValue());
                etapa.setValorTorre(((Integer) jSpinnerValorTorre.getValue()).intValue());
                etapa.setValorCavalo(((Integer)jSpinnerValorCavalo.getValue()).intValue());
                etapa.setValorBispo(((Integer) jSpinnerValorBispo.getValue()).intValue());
                etapa.setValorDama(((Integer)  jSpinnerValorDama.getValue()).intValue());            
            
                novoConjunto.setEtapaInicial(etapa);

                ConjuntoHeuristicoDAO.adiciona(novoConjunto, etapa);

                if (!faltaDadosAnotacao) {
                    
                    Anotacao anotacao = new Anotacao(HeuChess.usuario.getId(),
                                                     novoConjunto,
                                                    (Tipo) jComboBoxTipoAnotacao.getSelectedItem(),
                                                     titulo,
                                                     descricao);

                    AnotacaoDAO.adiciona(anotacao);

                    novoConjunto.getAnotacoes().add(anotacao);
                }
                
                ConexaoDBHeuChess.commit();        

                dispose();            
                HeuChess.telaPrincipal.fechandoTelaNovoConjuntoHeuristico(novoConjunto);
            
            } catch (Exception e) {
                HeuChess.desfazTransacao(e);
                
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                UtilsGUI.dialogoErro(this, "Erro ao tentar criar o Conjunto Heuristico no Banco de Dados\nOperação Cancelada!");
            }
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        HeuChess.ajuda.abre(this, "TelaNovoConjuntoHeuristico");
    }//GEN-LAST:event_jButtonAjudaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JComboBox jComboBoxTipoAnotacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIcone;
    private javax.swing.JLabel jLabelTotalCaracteres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPasso1;
    private javax.swing.JPanel jPanelPasso2;
    private javax.swing.JPanel jPanelPasso3;
    private javax.swing.JPanel jPanelPasso4;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderNivelComplexidade;
    private javax.swing.JSpinner jSpinnerValorBispo;
    private javax.swing.JSpinner jSpinnerValorCavalo;
    private javax.swing.JSpinner jSpinnerValorDama;
    private javax.swing.JSpinner jSpinnerValorPeao;
    private javax.swing.JSpinner jSpinnerValorTorre;
    private javax.swing.JTextArea jTextAreaExplicacaoComplexidade;
    private javax.swing.JTextArea jTextAreaTextoAnotacao;
    private javax.swing.JTextField jTextFieldNomeConjuntoHeuristico;
    private javax.swing.JTextField jTextFieldTituloAnotacao;
    private javax.swing.JTextField jTextFieldValorRei;
    // End of variables declaration//GEN-END:variables
}
